/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mini.project;

public class App {
  public String getGreeting() {

    return "Hello world.1.";


  }

  public static void main(String[] args) {
  System.out.println("오호라...!!!");
    System.out.print("유아람!");

  }
}
